name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Versions
        run: |
          node -v
          pnpm -v

      - name: Install (all workspaces)
        run: pnpm -r install --frozen-lockfile=false

      - name: List workspace
        run: |
          ls -la
          echo "--- pnpm-workspace.yaml ---"
          cat pnpm-workspace.yaml || true
          echo "--- engine package.json ---"
          cat packages/engine/package.json

      - name: Build (engine)
        run: pnpm --filter @solitaire/engine run build

      - name: Test (engine, verbose)
        run: pnpm --filter @solitaire/engine test --reporter=verbose

