name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Versions
        run: |
          pnpm -v
          node -v

      - name: Install (all workspaces)
        run: pnpm install

      - name: List workspace
        run: pnpm -w list --depth -1

      - name: Build (engine)
        run: pnpm --filter @solitaire/engine run build

      - name: Test (engine, verbose)
        run: pnpm --filter @solitaire/engine test -- --reporter=verbose

      - name: Coverage (engine)
        run: pnpm --filter @solitaire/engine run coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-node-${{ matrix.node }}
          path: packages/engine/coverage
