name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Install
        run: pnpm install

      - name: Build (engine)
        run: pnpm --filter @solitaire/engine run build

      - name: Test (engine)
        run: pnpm --filter @solitaire/engine test
