name: CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]
    name: test (Node ${{ matrix.node }})

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Versions
        run: |
          node -v
          pnpm -v

      - name: Install (all workspaces)
        run: pnpm -r install --frozen-lockfile=false

      - name: Build (engine)
        run: pnpm --filter @solitaire/engine run build

      - name: Test (engine, verbose)
        run: pnpm --filter @solitaire/engine test --reporter=verbose
